# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'googleMapApi' do
# Comment the next line if you don't want to use dynamic frameworks
use_frameworks!

# Pods for mapStanford
pod 'GooglePlaces'
pod 'GooglePlacePicker'
pod 'GoogleMaps'

end
