# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'messageApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for messageApp
pod 'SwiftyJSON'
pod 'Alamofire'
pod 'SVProgressHUD'
pod 'Firebase/Core'
pod 'Firebase'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Storage'

end

